<?php
/**
 * @file
 * fcl_ribbons_holiday_search_tiles.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function fcl_ribbons_holiday_search_tiles_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_holiday_tiles_more_results'.
  $field_bases['field_holiday_tiles_more_results'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_holiday_tiles_more_results',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        0 => '',
        1 => '',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_boolean',
  );

  // Exported field_base: 'field_holiday_tiles_more_text'.
  $field_bases['field_holiday_tiles_more_text'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_holiday_tiles_more_text',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_holiday_tiles_more_url'.
  $field_bases['field_holiday_tiles_more_url'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_holiday_tiles_more_url',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_holiday_tiles_results'.
  $field_bases['field_holiday_tiles_results'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_holiday_tiles_results',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        3 => 'Three tiles (one row)',
        6 => 'Six tiles (two rows)',
        9 => 'Nine tiles (three rows)',
        12 => '12 tiles (four rows)',
        15 => '15 tiles (five rows)',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_integer',
  );

  // Exported field_base: 'field_holiday_tiles_types'.
  $field_bases['field_holiday_tiles_types'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_holiday_tiles_types',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 1024,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
